name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "False"
          COMMIT_EMAIL: "aviral.robin@gmail.com"
          COMMIT_USERNAME: "aviralrabbit1"
          COMMIT_MESSAGE: "Update waka metrics"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "False"
          IGNORED_REPOS: "ml-model-for-gene-expression-of-prostate-cancer"
          SYMBOL_VERSION: 3
